name: generate snake

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: generate snake svgs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 3urkii
          outputs: |
            dist/github-snake-mocha.svg?color_snake=%23cba6f7&color_dots=%231e1e2e,%2345475a,%237f849c,%2389b4fa,%23cba6f7
            dist/github-snake-latte.svg?color_snake=%238839ef&color_dots=%23eff1f5,%23bcc0cc,%238c8fa1,%231e66f5,%238839ef

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
